### ISSUE TITLE
error on ubuntu 20.04

### ISSUE THREAD

**Issue by Samamuse** [marc-gedik/ElectronDeezer#6]
Hi!
I'm getting an error when I try to launch the app 

`(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
(electron) 'setUserAgent function' is deprecated and will be removed. Please use 'userAgent property' instead.`

Should we need a specific electron version to launch it ?

**Comment by marc-gedik** [comment]
Hi @Samamuse ! Thank you for the issue.

I don't have access to an ubuntu machine on hand, I just tried an "online" version of ubuntu, do you have the tray icon that appears? Seems that we need to double click on it to open it. I will try to fix that.

**Comment by Samamuse** [comment]
the tray icon is present, but nothing happen when I try to click on it. Nothing in the terminal too.
Thank's !
